/*var mongoose = require('mongoose');
var RedeSegurancaSchema = new mongoose.Schema(
    {
        enderecoMac: String,
        speedPlacaDeRede: String,
        localAddress: String,
        gatewayEndereco: String,
        mascara: String,
        servidorDNS: String,
        useDhcp: Boolean,
        dhcp: String,
        hostname: String,
        forceConfiguredGateway: Boolean,
        usarVerificacaoICMP: Boolean,
        icmp1: String,
        icmp2: String,
        icmp3: String,
        senhaAdministrador: String,
        unmsServerPwd: String,
        useUNMSServerPwd: Boolean,
        nomeDoSistema: String,
        localSistema: String,
        contatoSistema: String,
        dispositivosConectados: String,
        rasmanGIpAddress: String,
        rasmanGIpPort:String,
        AutoUpdateARPCache: Boolean,
        tcpMss: Number,
        servAtualPorto: Number,
        ativarTelnet: Boolean,
        habilitarFtpServidor: Boolean,
        habilitarHttpServidor: Boolean,
        httpPort: Number,
        useHTTPS: Boolean,
        httpsPort: Number,
        httpTempoAtualizacao: Number,
        paginaPadraoHttp: String,
        ativarDicasFerramenta: Boolean,
        enableHttpCaching: Boolean,
        ocultarDispHttpLigacaoFuncoes: Boolean,
        enableUNMSServer: Boolean,
        UNMSPort: Number,
        useRCCMD2Armadilhas: Boolean,
        ativarListenerRCCMD: Boolean,
        portListenerRCCMD: Number,
        rccmdTimeout: Number,
        useRCCMDSSL: Boolean,
        ativarModBusOverIP: Boolean,
        enderecoModBusSlave: Number,
        modoModBus: String,
        saveLogFilesAutomatically: Boolean
    }
);

module.exports = mongoose.model('RedeSegurancaSchema', RedeSegurancaSchema);
*/