var sqlite3 = require('sqlite3').verbose();  
var db = new sqlite3.Database('equalizerdb');
var init = function () {
    console.log("Criando DB");
    db.serialize(function () {
        db.run("CREATE TABLE IF NOT EXISTS AlarmLog ( id INTEGER PRIMARY KEY AUTOINCREMENT, dataHora TEXT, descricao TEXT, emailEnviado INTEGER, n_ocorrencias INTEGER DEFAULT 0 )");
        db.run("CREATE TABLE IF NOT EXISTS AlarmeConfig ( id INTEGER PRIMARY KEY AUTOINCREMENT, tipo_modulo TEXT, nivel_alert_tensao_max REAL, nivel_alert_tensao_min REAL, nivel_alert_temp_max REAL, nivel_alert_temp_min REAL, nivel_alert_impedancia_max REAL, nivel_alert_impedancia_min REAL, nivel_max_tensao_ativo INTEGER, nivel_max_tensao_val REAL, alarme_nivel_tensao_max REAL, alarme_nivel_tensao_min REAL, alarme_nivel_temp_max REAL, alarme_nivel_temp_min REAL, alarme_nivel_imped_max REAL, alarme_nivel_imped_min REAL, alarme_nivel_tensaoBarr_min REAL, alarme_nivel_tensaoBarr_max REAL, alarme_nivel_target_min REAL, alarme_nivel_target_max REAL )");
        db.run("CREATE TABLE IF NOT EXISTS DataLog ( id INTEGER PRIMARY KEY AUTOINCREMENT, dataHora TEXT, string TEXT, bateria TEXT, temperatura REAL, impedancia REAL, tensao REAL, equalizacao REAL )");
        db.run("CREATE TABLE IF NOT EXISTS DataLogRT ( idINTEGER PRIMARY KEY AUTOINCREMENT, dataHoraTEXT, stringTEXT, bateriaTEXT, temperaturaREAL, impedanciaREAL, tensaoREAL, equalizacaoREAL )");
        db.run("CREATE TABLE IF NOT EXISTS EmailServer (id INTEGER PRIMARY KEY AUTOINCREMENT, server TEXT, portaSMTP INTEGER, usarCriptografiaTLS INTEGER, email TEXT, assunto TEXT, usarAutenticacao INTEGER, login TEXT, senha TEXT)");
        db.run("CREATE TABLE IF NOT EXISTS Modulo ( id INTEGER PRIMARY KEY AUTOINCREMENT, descricao TEXT, tensao_nominal REAL, capacidade_nominal INTEGER, n_strings INTEGER, n_baterias_por_strings INTEGER, contato TEXT, localizacao TEXT, fabricante TEXT, tipo TEXT, data_instalacao TEXT, conf_alarme_id INTEGER, FOREIGN KEY(conf_alarme_id) REFERENCES AlarmeConfig(id) )");
        db.run("CREATE TABLE IF NOT EXISTS Parameters ( id INTEGER PRIMARY KEY AUTOINCREMENT, avg_last TEXT, duty_min TEXT, duty_max TEXT, cte_index TEXT, delay TEXT, num_cycles_var_read TEXT, bus_voltage TEXT, save_log_time TEXT, disk_capacity TEXT, param1 TEXT, param2 TEXT, param3 TEXT, param4 TEXT, param5 TEXT, param6 TEXT, param7 TEXT, param8 TEXT, param9 TEXT, param10 TEXT )");
        db.run("CREATE TABLE IF NOT EXISTS RedeSeguranca (id INTEGER PRIMARY KEY AUTOINCREMENT, mac, velocidadePlacaRede TEXT, localAddress TEXT, gateway TEXT, mascara TEXT, servidorDNS TEXT, nomeDoSistema TEXT, localDoSistema TEXT, contatoDoSistema TEXT, httpPort INTEGER, useHttps INTEGER, httpsPort INTEGER, httpTempoDeAtualizacao INTEGER, paginaPadraoHttp TEXT)");
        db.run("CREATE TABLE IF NOT EXISTS TimeServer (id INTEGER PRIMARY KEY AUTOINCREMENT, timeServerAddress1 TEXT, timeServerAddress1_complemento TEXT, timeServerAddress2 TEXT, timeServerAddress2_complemento TEXT, timeServerAddress3 TEXT, timeServerAddress3_complemento TEXT, connectionRetries INTEGER, timeZone TEXT, automAdjustTimeDaylightSavingChanges INTEGER)");
        db.run("CREATE TABLE IF NOT EXISTS Usuario (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT, sobreNome TEXT, telefone TEXT, email TEXT, senha TEXT, acesso TEXT)");
        db.run("CREATE TABLE IF NOT EXISTS ApelidoString ( String TEXT, Apelido TEXT )");

        //Triggers
        db.run("CREATE TRIGGER IF NOT EXISTS alertOcurrences AFTER UPDATE ON DataLogRT BEGIN UPDATE ALARMLOG SET N_OCORRENCIAS = N_OCORRENCIAS + 1 WHERE DATE(DATAHORA) = DATE(datetime('now','localtime')) AND DESCRICAO LIKE '%' || NEW.string || '-' || NEW .bateria ||'%'; END");
        db.run("CREATE TRIGGER IF NOT EXISTS alertOcurrencesParam AFTER UPDATE ON Parameters BEGIN UPDATE ALARMLOG SET N_OCORRENCIAS = N_OCORRENCIAS + 1 WHERE DATE(DATAHORA) = DATE(datetime('now','localtime')) AND (DESCRICAO LIKE '%Barramento%' OR DESCRICAO LIKE '%Target%'); END");
        db.run("CREATE TRIGGER IF NOT EXISTS raiseAlertTensao AFTER UPDATE ON DataLogRT WHEN (SELECT COUNT(*) FROM ALARMLOG WHERE DATE(DATAHORA) = DATE(datetime('now','localtime')) AND DESCRICAO LIKE '%Alerta de Tensão em ' || NEW.string || '-' || NEW .bateria ||'%') <= 0 BEGIN INSERT INTO ALARMLOG(dataHora, descricao, emailEnviado, n_ocorrencias) SELECT datetime('now','localtime') , 'Alerta de Tensão em ' || NEW.string || '-' || NEW .bateria || ', Mínima: '|| (NEW.tensao / 1000) ||' de ' || ALARME_NIVEL_TENSAO_MIN , 0 , 1 FROM ALARMECONFIG WHERE (NEW.tensao / 1000) < ALARME_NIVEL_TENSAO_MIN UNION SELECT datetime('now','localtime'), 'Alerta de Tensão em ' || NEW.string || '-' || NEW .bateria || ', Máxima: '|| (NEW.tensao / 1000) ||' de ' || ALARME_NIVEL_TENSAO_MAX , 0 , 1 FROM ALARMECONFIG WHERE (NEW.tensao / 1000) > ALARME_NIVEL_TENSAO_MAX; END");
        db.run("CREATE TRIGGER IF NOT EXISTS raiseAlertTemp AFTER UPDATE ON DataLogRT WHEN (SELECT COUNT(*) FROM ALARMLOG WHERE DATE(DATAHORA) = DATE(datetime('now','localtime')) AND DESCRICAO LIKE '%Alerta de Temperatura em ' || NEW.string || '-' || NEW .bateria ||'%') <= 0 BEGIN INSERT INTO ALARMLOG(dataHora, descricao, emailEnviado, n_ocorrencias) SELECT datetime('now','localtime'), 'Alerta de Temperatura em ' || NEW.string || '-' || NEW .bateria || ', Mínima: '|| (NEW.temperatura / 10) ||' de ' || ALARME_NIVEL_Temp_MIN , 0 , 1 FROM ALARMECONFIG WHERE (NEW.temperatura / 10) < ALARME_NIVEL_Temp_MIN UNION SELECT datetime('now','localtime'), 'Alerta de Temperatura em ' || NEW.string || '-' || NEW .bateria || ', Máxima: '|| (NEW.temperatura / 10) ||' de ' || ALARME_NIVEL_Temp_MAX , 0 , 1 FROM ALARMECONFIG WHERE (NEW.temperatura / 10) > ALARME_NIVEL_Temp_MAX; END");
        db.run("CREATE TRIGGER IF NOT EXISTS raiseAlertImp AFTER UPDATE ON DataLogRT WHEN (SELECT COUNT(*) FROM ALARMLOG WHERE DATE(DATAHORA) = DATE(datetime('now','localtime')) AND DESCRICAO LIKE '%Alerta de Impedância em ' || NEW.string || '-' || NEW .bateria ||'%') <= 0 BEGIN INSERT INTO ALARMLOG(dataHora, descricao, emailEnviado, n_ocorrencias) SELECT datetime('now','localtime'), 'Alerta de Impedância em ' || NEW.string || '-' || NEW .bateria || ', Mínima: '|| (NEW.impedancia / 100) ||' de ' || ALARME_NIVEL_IMPED_MIN, 0, 1 FROM ALARMECONFIG WHERE (NEW.impedancia / 100) < ALARME_NIVEL_IMPED_MIN UNION SELECT datetime('now','localtime'), 'Alerta de Impedância em ' || NEW.string || '-' || NEW .bateria || ', Máxima: '|| (NEW.impedancia / 100) ||' de ' || ALARME_NIVEL_IMPED_MAX, 0, 1 FROM ALARMECONFIG WHERE (NEW.impedancia / 100) > ALARME_NIVEL_IMPED_MAX ; END");
        db.run("CREATE TRIGGER IF NOT EXISTS raiseAlertParamBarramento AFTER UPDATE ON Parameters WHEN (SELECT COUNT(*) FROM ALARMLOG WHERE DATE(DATAHORA) = DATE(datetime('now','localtime')) AND DESCRICAO LIKE '%Barramento%') <= 0 BEGIN INSERT INTO ALARMLOG(dataHora, descricao, emailEnviado, n_ocorrencias) SELECT datetime('now','localtime') , 'Alerta de Tensão de Barramento, Mínima: '|| (NEW.bus_voltage / 1000) ||' de ' || ALARME_NIVEL_TENSAOBARR_MIN, 0, 1 FROM ALARMECONFIG WHERE (NEW.bus_voltage / 1000) < ALARME_NIVEL_TENSAOBARR_MIN UNION SELECT datetime('now','localtime'), 'Alerta de Tensão de Barramento, Máxima: '|| (NEW.bus_voltage / 1000) ||' de ' || ALARME_NIVEL_TENSAOBARR_MAX, 0, 1 FROM ALARMECONFIG WHERE (NEW.bus_voltage / 1000) > ALARME_NIVEL_TENSAOBARR_MAX; END");
        db.run("CREATE TRIGGER IF NOT EXISTS raiseAlertParamTarget AFTER UPDATE ON Parameters WHEN (SELECT COUNT(*) FROM ALARMLOG WHERE DATE(DATAHORA) = DATE(datetime('now','localtime')) AND DESCRICAO LIKE '%Target%') <= 0 BEGIN INSERT INTO ALARMLOG(dataHora, descricao, emailEnviado, n_ocorrencias) SELECT datetime('now','localtime') , 'Alerta de Target, Mínima: '|| (NEW.AVG_LAST / 1000) ||' de ' || ALARME_NIVEL_TARGET_MIN, 0, 1 FROM ALARMECONFIG WHERE (NEW.AVG_LAST / 1000) < ALARME_NIVEL_TARGET_MIN UNION SELECT datetime('now','localtime'), 'Alerta de Target, Máxima: '|| (NEW.AVG_LAST / 1000) ||' de ' || ALARME_NIVEL_TARGET_MAX, 0, 1 FROM ALARMECONFIG WHERE (NEW.AVG_LAST / 1000) > ALARME_NIVEL_TARGET_MAX; END");
        db.run("CREATE TRIGGER IF NOT EXISTS raiseAlertParamDiskCapacity AFTER UPDATE ON Parameters WHEN (NEW.disk_capacity > 95 and (SELECT COUNT(*) FROM ALARMLOG WHERE DATE(DATAHORA) = DATE(datetime('now','localtime')) AND DESCRICAO LIKE 'Alerta de Disco, utilização em ' || NEW.disk_capacity || ' %') <= 0) BEGIN INSERT INTO ALARMLOG(dataHora, descricao, emailEnviado, n_ocorrencias) SELECT datetime('now','localtime') , 'Alerta de Disco, utilização em ' || NEW.disk_capacity || ' %', 0, 1; END");

        //INDEXES
        db.run("CREATE INDEX IF NOT EXISTS idx_alarmlog_ata ON AlarmLog (dataHora)");
        db.run("CREATE INDEX IF NOT EXISTS idx_alarmlog_descricao ON AlarmLog (descricao)");

    });
    db.close();
};
module.exports.init = init;